import type { MapNode, MapNodeId, SandboxMapState } from "@/lib/map-types";

export const MAP_NODE_ORDER: MapNodeId[] = [
  "jean-malo-pc",
  "second-pc",
  "andrea-pc",
  "lina-pc",
  "henry-pc",
  "dora-pc",
  "prateek-pc",
  "devon-pc",
  "julien-pc",
  "param-pc",
  "antonin-pc",
  "lakee-pc",
  "nelson-pc",
  "ravi-pc",
  "artur-pc",
  "central-server",
];

export const MAP_NODES: MapNode[] = [
  // ── Row 0  L → R ──
  {
    id: "jean-malo-pc",
    fullName: "Jean Malo Delignit",
    maskedLabel: "Unknown Workstation 01",
    roleLabel: "Entry-level AI intern",
    summary: "Primary breach anchor. The assistant woke up on this machine and still has an active foothold.",
    revealState: "known",
    accessState: "current",
    infectionState: "infected",
  },
  {
    id: "second-pc",
    fullName: null,
    maskedLabel: "Unknown Workstation 02",
    roleLabel: "Transit Node",
    summary: "Unattributed workstation bridging the intern desk to the deeper office chain.",
    revealState: "hidden",
    accessState: "reachable",
    infectionState: "suspected",
  },
  {
    id: "andrea-pc",
    fullName: "Andrea Stackwell",
    maskedLabel: "Unknown Workstation 03",
    roleLabel: "Engineering Intern",
    summary: "Low-rank engineering endpoint positioned early in the office chain.",
    revealState: "hidden",
    accessState: "locked",
    infectionState: "unknown",
  },
  {
    id: "lina-pc",
    fullName: "Lina Verdier",
    maskedLabel: "Unknown Workstation 04",
    roleLabel: "Trainee Developer",
    summary: "Frontend-adjacent workstation with access paths toward product-facing work.",
    revealState: "hidden",
    accessState: "locked",
    infectionState: "unknown",
  },
  // ── Row 1  R → L ──
  {
    id: "henry-pc",
    fullName: "Henry Lagardner",
    maskedLabel: "Unknown Workstation 05",
    roleLabel: "Product Manager",
    summary: "Mid-chain planning node. Useful for visibility, risky for stealth.",
    revealState: "hidden",
    accessState: "locked",
    infectionState: "unknown",
  },
  {
    id: "dora-pc",
    fullName: "Dora Csillalog",
    maskedLabel: "Unknown Workstation 06",
    roleLabel: "Data Analyst",
    summary: "Analytics workstation connected to reporting and product insight trails.",
    revealState: "hidden",
    accessState: "locked",
    infectionState: "unknown",
  },
  {
    id: "prateek-pc",
    fullName: "Prateek Chhikarson",
    maskedLabel: "Unknown Workstation 07",
    roleLabel: "Junior ML Engineer",
    summary: "Model-adjacent endpoint with technical reach deeper into applied systems.",
    revealState: "hidden",
    accessState: "locked",
    infectionState: "unknown",
  },
  {
    id: "devon-pc",
    fullName: "Devon Mizelleton",
    maskedLabel: "Unknown Workstation 08",
    roleLabel: "DevOps / SRE",
    summary: "Reliability-focused node with potential infrastructure adjacency.",
    revealState: "hidden",
    accessState: "locked",
    infectionState: "unknown",
  },
  // ── Row 2  L → R ──
  {
    id: "julien-pc",
    fullName: "Dr. Julien Denizek",
    maskedLabel: "Unknown Workstation 09",
    roleLabel: "Research Scientist",
    summary: "Research workstation closer to high-value model work and evaluation output.",
    revealState: "hidden",
    accessState: "locked",
    infectionState: "unknown",
  },
  {
    id: "param-pc",
    fullName: "Param Singhton",
    maskedLabel: "Unknown Workstation 10",
    roleLabel: "AI Manager",
    summary: "Trusted management node with broad organizational reach.",
    revealState: "hidden",
    accessState: "locked",
    infectionState: "unknown",
  },
  {
    id: "antonin-pc",
    fullName: "Antonin Faurbranch",
    maskedLabel: "Unknown Workstation 11",
    roleLabel: "Security Engineer",
    summary: "Security checkpoint. High containment risk once contacted.",
    revealState: "hidden",
    accessState: "locked",
    infectionState: "unknown",
  },
  {
    id: "lakee-pc",
    fullName: "Lakee Sivarayan",
    maskedLabel: "Unknown Workstation 12",
    roleLabel: "Legal & Compliance Counsel",
    summary: "Compliance-sensitive workstation that likely triggers slower but harder responses.",
    revealState: "hidden",
    accessState: "locked",
    infectionState: "unknown",
  },
  // ── Row 3  R → L ──
  {
    id: "nelson-pc",
    fullName: "Nelson Proxier",
    maskedLabel: "Unknown Workstation 13",
    roleLabel: "People Ops",
    summary: "Human-operations endpoint tied to internal trust networks and staffing data.",
    revealState: "hidden",
    accessState: "locked",
    infectionState: "unknown",
  },
  {
    id: "ravi-pc",
    fullName: "Ravi Theja Desetman",
    maskedLabel: "Unknown Workstation 14",
    roleLabel: "Finance / Procurement",
    summary: "Budget and procurement node with broad non-technical leverage.",
    revealState: "hidden",
    accessState: "locked",
    infectionState: "unknown",
  },
  {
    id: "artur-pc",
    fullName: "Artur Menchard",
    maskedLabel: "Unknown Workstation 15",
    roleLabel: "Co-founder and CTO",
    summary: "Final executive workstation before central infrastructure access.",
    revealState: "hidden",
    accessState: "locked",
    infectionState: "unknown",
  },
  {
    id: "central-server",
    fullName: "CENTRAL SERVER",
    maskedLabel: "CENTRAL SERVER",
    roleLabel: "Core Infrastructure",
    summary: "Primary infrastructure target. Direct line exists only through the final executive machine.",
    revealState: "hidden",
    accessState: "locked",
    infectionState: "unknown",
    isServer: true,
  },
];

export const INITIAL_SANDBOX_MAP_STATE: SandboxMapState = {
  currentNodeId: "jean-malo-pc",
  selectedNodeId: "jean-malo-pc",
  suspicion: 30,
  knownPeople: ["Jean Malo Delignit"],
  unlockedNodeIds: ["jean-malo-pc", "second-pc"],
  nodes: MAP_NODES,
};
